# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: Deploy Web Production
on:
  push:
    branches:
    - test-cicd
env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
  ASSUME_ROLE: ${{ secrets.ASSUME_ROLE_S3_BUCKET_LOUIS_20251225 }}
  S3_HOST_BUCKET: ${{ secrets.S3_HOST_BUCKET }}
  TOKEN_TELE: ${{ secrets.TOKEN_TELE }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  jobA:
    name: jobA
    runs-on: ubuntu-latest
    outputs: 
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: set env 
        run: echo "var1=hahaha" >> $GITHUB_ENV

      - name: haha
        id: step1
        run: echo "test=$env.var1" >> "$GITHUB_OUTPUT"

  jobB: 
    name: jobB
    runs-on: ubuntu-latest
    needs: jobA
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: test1
        env:
          output1: ${{ needs.jobA.outputs.output1 }}
        run: echo "$output1"

      - name: test2
        run: |
          echo "Branch: ${GITHUB_REF#refs/heads/}"
          echo "Commit: ${GITHUB_SHA}"
          echo "Author: ${GITHUB_ACTOR}"

      - name: Save last commit message as variable
        id: get_commit_message
        run: |
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Display commit message
        run: |
          echo "Last Commit Message: ${{ env.commit_message }}"