# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: Deploy Web Production
on:
  push:
    branches:
    - test-cicd
env:
  AWS_REGION : ${{ secrets.AWS_REGION }}
  ASSUME_ROLE: ${{ secrets.ASSUME_ROLE_S3_BUCKET_LOUIS_20251225 }}
  S3_HOST_BUCKET: ${{ secrets.S3_HOST_BUCKET }}
  TOKEN_TELE: ${{ secrets.TOKEN_TELE }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  jobA:
    name: jobA
    runs-on: ubuntu-latest
    outputs: 
      output1: ${{ steps.step1.outputs.test }}
    steps: 
      - id: step1
        env: 
          var1 : "Louis dep trai"
        run: echo "test=$var1" >> "$GITHUB_OUTPUT"

  jobB: 
    name: jobB
    runs-on: ubuntu-latest
    needs: jobA
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: test1
        env: 
          output1: ${{ needs.jobA.outputs.output1 }}
        run: echo "$output1"
      - name: test2
        run: |
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "Branch: ${GITHUB_REF#refs/heads/}"
          echo "Commit: ${GITHUB_SHA}"
          echo "Author: ${GITHUB_ACTOR}"
          echo "message: $commit_message"